name: ngobrolapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.20.0
  google_sign_in: 5.4.0
  firebase_auth: 3.6.2
  lottie: 1.4.0
  introduction_screen: 3.0.2
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.3.0
  get_storage: 2.0.3
  cloud_firestore: 3.4.3
  intl: 0.17.0
  image_picker: 0.8.5+3
  firebase_storage: 10.3.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

