// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlhD_E8Fz1TIY3KjFHWbKSAqnKjNuY79o',
    appId: '1:50515140808:web:6d5f04c0bfe5c2dbf285fd',
    messagingSenderId: '50515140808',
    projectId: 'ngobrolapps-whyildan',
    authDomain: 'ngobrolapps-whyildan.firebaseapp.com',
    storageBucket: 'ngobrolapps-whyildan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU5V196ub_VyrZIfzSHZqET_8CUmP6TYY',
    appId: '1:50515140808:android:26752619c3385275f285fd',
    messagingSenderId: '50515140808',
    projectId: 'ngobrolapps-whyildan',
    storageBucket: 'ngobrolapps-whyildan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxx9Kl9GEWS7RyAvfhAeoVGpAy06faunk',
    appId: '1:50515140808:ios:d9fb0f1eac204a66f285fd',
    messagingSenderId: '50515140808',
    projectId: 'ngobrolapps-whyildan',
    storageBucket: 'ngobrolapps-whyildan.appspot.com',
    androidClientId: '50515140808-s9pthr5t2c587g994shaiop03tbkn1l1.apps.googleusercontent.com',
    iosClientId: '50515140808-shn6o9tt15v5qtbgoepa4leh0dk9qj60.apps.googleusercontent.com',
    iosBundleId: 'com.whyldanprtama.ngobrolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxx9Kl9GEWS7RyAvfhAeoVGpAy06faunk',
    appId: '1:50515140808:ios:d9fb0f1eac204a66f285fd',
    messagingSenderId: '50515140808',
    projectId: 'ngobrolapps-whyildan',
    storageBucket: 'ngobrolapps-whyildan.appspot.com',
    androidClientId: '50515140808-s9pthr5t2c587g994shaiop03tbkn1l1.apps.googleusercontent.com',
    iosClientId: '50515140808-shn6o9tt15v5qtbgoepa4leh0dk9qj60.apps.googleusercontent.com',
    iosBundleId: 'com.whyldanprtama.ngobrolapp',
  );
}
